config/routes.rb
Rails.application.routes.draw do

  # get 'animals/index'
  # get 'animals/show'
  devise_for :users
  root to: "animals#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  #  root to: 'pages#index'


  resources :animals do
    collection do
      get :my_animals
    end
  end

  resources :bookings do
    collection do
      get :my_bookings
    end
  end

  resources :animals do
    resources :animal_abilities, only: [:new, :create]
    resources :bookings, only: [:new, :create, :index]
  end

end

app/models/ability.rb
class Ability < ApplicationRecord
  has_many :animal_abilities
  has_many :animals, through: :animal_abilities

  validates :name, presence: true, uniqueness: true
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :animal_abilities
  has_many :abilities, through: :animal_abilities

  validates :name, :location, :age, :price, presence: true
  validates :age, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: { greater_than: 0 }
  validates :name, uniqueness: true
end

app/models/animal_ability.rb
class AnimalAbility < ApplicationRecord
  belongs_to :animal
  belongs_to :ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :animal
  validates :start_date, presence: true
  validates :end_date, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :animals
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animal_abilities_controller.rb
class AnimalAbilitiesController < ApplicationController
  def new
    @animal = Animal.find(params[:animal_id])
    @animal_ability = AnimalAbility.new
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @abilities = Ability.where(id: params[:animal_ability][:ability_id])
    @abilities.each do |ability|
      animal_ability = AnimalAbility.new(animal: @animal, ability: ability)
      animal_ability.save
  end
  redirect_to animals_path
end

# private

#   def render_new
#     @animal_ability = AnimalAbility.new
#     @animal_ability.errors.add(:base, "You have already selected this ability")
#     render :new, status: :unprocessable_entity
#   end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @animals = Animal.all.order('created_at DESC')

    if params[:search].present?
      @animals = @animals.where('name ILIKE ?', "%#{params[:search]}%")
    end

    if params[:age].present?
      age_range = params[:age].split('-')
      @animals = @animals.where(age: age_range[0]..age_range[1])
    end

    if params[:ability].present?
      @animals = @animals.joins(:abilities).where(abilities: { name: params[:ability] })
    end
  end

  def show
    @booking = Booking.new
    @animal = Animal.find(params[:id])

  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user

    if @animal.save
      redirect_to new_animal_animal_ability_path(@animal)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    @animal.user = current_user
  end

  def update
    @animal = Animal.find(params[:id])
    @animal.user = current_user

    if @animal.update(animal_params)
      redirect_to animal_path(@animal)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def my_animals
    @animals = current_user.animals
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :location, :age, :price, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user_id: current_user.id)
  end


  def new
    @animal = Animal.find(params[:animal_id])
    @booking = Booking.new
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.animal = @animal
    # @booking.total_price = total_price(@booking)
    if @booking.save
      redirect_to my_bookings_bookings_path(@animal)
    else
      redirect_to animal_path(@animal)
    end
  end

  def my_bookings
    @bookings = current_user.bookings
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :booking_status, :user_id, :animal_id)
  end

  # def total_price(booking)
  #   return unless booking.start_date && booking.end_date

  #   number_of_days = (booking.end_date - booking.start_date).to_i
  #   price_per_day = @animal.price

  #   number_of_days * price_per_day
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animal_abilities/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h1 class="ability">Add abilities to <%= @animal.name %></h1>

      <%= simple_form_for [@animal, @animal_ability] do |f| %>

        <%= f.association :ability, as: :check_boxes, collection: Ability.all, input_html: { class: "tag-selector" }, item_wrapper_class: 'tag-item' %>

        <%= f.submit "Add ability", class: 'btn btn-primary rounded-pill' %>
      <% end %>
    </div>
  </div>
</div>

app/views/animals/_book_form.html.erb
<%= simple_form_for [@animal, @booking] do |f| %>
  <%= f.input :start_date, as: :string, input_html: { id: 'start_date', data: { controller: 'datepicker' } } %>
  <%= f.input :end_date, as: :string, input_html: { id: 'end_date', data: { controller: 'datepicker', dateFormate: 'DD-MM-YYYY' } } %>
  <p id="stay_duration"></p>
  <p id="total_price"></p>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

<script>
  const startDateInput = document.getElementById('start_date');
  const endDateInput = document.getElementById('end_date');
  const stayDurationParagraph = document.getElementById('stay_duration');
  const totalPriceParagraph = document.getElementById('total_price');
const pricePerDay = parseFloat(document.querySelector('.animal-price').textContent.replace('Price is: $', ''));


  function calculateStayDuration() {
    const startDate = new Date(startDateInput.value);
    const endDate = new Date(endDateInput.value);
    const duration = Math.ceil((endDate - startDate) / (1000 * 60 * 60 * 24));

    if (!isNaN(duration)) {
      stayDurationParagraph.textContent = `Stay duration: ${duration} days`;
      const totalPrice = pricePerDay * duration;
      totalPriceParagraph.textContent = `Total price: ${totalPrice} USD`;
    }
  }

  startDateInput.addEventListener('change', calculateStayDuration);
  endDateInput.addEventListener('change', calculateStayDuration);
</script>

app/views/animals/_form.html.erb
<%= simple_form_for(@animal) do |f| %>
  <%= f.input :name %>
  <%= f.input :image, as: :file%>
  <%= f.input :age %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.submit   %>


<% end %>

app/views/animals/_sidebar.html.erb
<div class="container d-flex">
  <div class = "row">
    <div id="sidebar" class="d-flex flex-column flex-shrink-0 p-3 col-3 bg-white min-vh-100">
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-primary dropdown-toggle mt-3" data-bs-toggle="dropdown" aria-expanded="false">
          Age
        </button>
        <ul class="dropdown-menu text-center">
  <li><%= link_to '0 - 29', animals_path(age: '0-29'), class: "dropdown-item first" %></li>
  <li><%= link_to '30 - 59', animals_path(age: '30-59'), class: "dropdown-item second" %></li>
  <li><%= link_to '59 - 80', animals_path(age: '59-80'), class: "dropdown-item third" %></li>
  <li><%= link_to '80 - 100', animals_path(age: '80-100'), class: "dropdown-item fourth" %></li>
  <li><%= link_to '100 +', animals_path(age: '100-'), class: "dropdown-item fifth" %></li>
</ul>
      </div>

      <div class="btn-group" role="group">
        <button type="button" class="btn btn-primary dropdown-toggle mt-4" data-bs-toggle="dropdown" aria-expanded="false">
          Ability
        </button>

         <ul class="dropdown-menu">
  <li><%= link_to 'Fire', animals_path(ability: 'Fire'), class: "dropdown-item" %></li>
  <li><%= link_to 'Water', animals_path(ability: 'Water'), class: "dropdown-item" %></li>
  <li><%= link_to 'Earth', animals_path(ability: 'Earth'), class: "dropdown-item" %></li>
  <li><%= link_to 'Air', animals_path(ability: 'Air'), class: "dropdown-item" %></li>
  <li><%= link_to 'Intellect', animals_path(ability: 'Intellect'), class: "dropdown-item" %></li>
  <li><%= link_to 'Strength', animals_path(ability: 'Strength'), class: "dropdown-item" %></li>
  <li><%= link_to 'Speed', animals_path(ability: 'Speed'), class: "dropdown-item" %></li>

        </ul>
      </div>

      <div class="btn-group" role="group">
        <button type="button" class="btn btn-primary dropdown-toggle mt-4" data-bs-toggle="dropdown" aria-expanded="false">
         Price
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="#">Dropdown link</a></li>
          <li><a class="dropdown-item" href="#">Dropdown link</a></li>
        </ul>
      </div>
    </div>

app/views/animals/edit.html.erb
<%= render 'form' %>

app/views/animals/index.html.erb
<div class="container top-header bg-white">
  <h2 class="dancing-script bounce-top" style="text-align:center">MagicMon <i class="fa-solid fa-dragon"></i></i></h2>
  <div class="container-fluid">
    <form class="d-flex" role="search" action="<%= animals_path %>" method="get">
  <input name="search" class="form-control me-2 rounded-pill" type="search" placeholder="Search for an animal..." aria-label="Search" style="border: none; box-shadow: 0 0 15px rgba(0,0,0,0.1);">
  <button class="btn btn-primary rounded-pill" type="submit" style="border: none; box-shadow: 0 0 15px rgba(0,0,0,0.2);">Search</button>
</form>
  </div>
</div>

<%# have changed the button %>

<%# abilities = %w[Fire Earth Water Air Intellect Strength Speed] %>

<%= render 'sidebar' %>



<div class='col-9 bg-white' style="display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-gap: 20px;

    ">

  <% @animals.each do |animal| %>

      <div class="card mt-3 animal-card"  >
        <%# Cloudinary Image %>
        <%# upload the image to Cloudinary %>
        <%= cl_image_tag animal.image.key, class: "card-img-top" if animal.image.attached? %>
        <div class="card-body  ">
          <h5 class="card-title"><%= link_to animal.name, animal_path(animal) %></h5>
          <p class="card-text"><%= animal.location %></p>
          <% animal.abilities.each do |ability| %>
            <a href="#" class="btn btn-success rounded-pill"><%=ability.name %></a>

          <% end %>
        </div>
      </div>

  <% end %>
</div>


<%# link to the new route %>
<%# <%= cl_image_tag(@animal.image.key) if @animal.image.attached? %>
</div>
</div>

app/views/animals/my_animals.html.erb
 <h1>My Animals</h1>

 <% @animals.each do |animal| %>

    <div class="card">
      <div class="row no-gutters">
        <div class="col-md-6 my-animal-card">
          <%= cl_image_tag(animal.image.key, class: "card-img")  if animal.image.attached?%>
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <h3 class="card-title"><%= animal.name %></h3>
            <p class="card-text">Located At <%= animal.location %></p>
            <p>  <%= animal.age %> Years old</p>
            <p>Price is: $<%= animal.price %></p>
            <% animal.abilities.each do |ability| %>
              <a href="#" class="btn btn-success rounded-pill"><%= ability.name %></a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/animals/new.html.erb
<%= render 'form' %>

app/views/animals/show.html.erb
<div class="card">
  <div class="row no-gutters">
    <div class="col-md-6">
      <%= cl_image_tag(@animal.image.key, class: "show-img")  if @animal.image.attached?%>
    </div>
    <div class="col-md-6">
      <div class="card-body">




        <h3 class="card-title"><%= @animal.name %></h3>
        <p class="card-text">Located At <%= @animal.location %></p>
        <p>  <%= @animal.age %> Years old</p>
        <p class='animal-price'>Price is: $<%= @animal.price %></p>
        <% @animal.abilities.each do |ability|  %>
        <a href="#" class="btn btn-success rounded-pill"><%= ability.name %></a>
        <% end %>

        <%= render 'book_form' %>




      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', animals_path, class: ' btn btn-secondary rounded-pill'  %>
    <%# link to edit %>

    <%= link_to 'Edit', edit_animal_path, class: 'btn btn-dark rounded-pill' if @animal.user == current_user %>

    <%# #link to make a booking %>



  </div>
</div>


<%#
if the user isnt signed in, the edit button should not show %>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
  <h1>Your Bookings</h1>
  <% @bookings.each do |booking| %>

    <div class="card">
      <div class="row no-gutters">
        <div class="col-md-6">
          <%= cl_image_tag(booking.animal.image.key, class: "card-img")  if booking.animal.image.attached?%>
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <h3 class="card-title"><%= booking.animal.name %></h3>
            <p class="card-text">Located At <%= booking.animal.location %></p>
            <p>  <%= booking.animal.age %> Years old</p>
            <p>Price is: $<%= booking.animal.price %></p>
            <p>Start Date: <%= booking.start_date %></p>
            <p>End Date: <%= booking.end_date %></p>
            <p>Total Price: <%= booking.total_price %>$</p>
            <% booking.animal.abilities.each do |ability| %>
              <a href="#" class="btn btn-primary"><%= ability.name %></a>
            <% end %>
          </div>
        </div>
      </div>
    </div>




            <% end %>

app/views/bookings/my_bookings.html.erb
 <h1>My Bookings</h1>

 <% @bookings.each do |booking| %>

    <div class="card">
      <div class="row no-gutters">
        <div class="col-md-6">
          <%= cl_image_tag(booking.animal.image.key, class: "card-img")  if booking.animal.image.attached?%>
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <h3 class="card-title"><%= booking.animal.name %></h3>
            <p class="card-text">Start date <%= booking.start_date %></p>
            <p>End date<%= booking.end_date %>
            </p>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/bookings/new.html.erb
<h1>
  This is the new booking page
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MagicMon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
  </head>


  <body class=''>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class='min-vh-100'>
      <div class='container'>
    <%= yield %>

      </div>




    </div>
<footer>
  <%= render 'shared/footer' %>
</footer>

  </body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_card.html.erb
<%# #create a card for each item %>



<div class="card border-dark rounded" style="width: 22rem; height:18rem">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title"></h5>
    <p class="card-text">The number of the animal</p>
    <a href="#" class="btn btn-primary">Type 1</a>
    <a href="#" class="btn btn-warning">Type 2</a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->

  <!-- Footer -->
  <footer
          class="text-center text-lg-start text-white"
          style="background-color: #929fba;  width:100%;"
          >
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Magicmon
            </h6>
            <p>
             Welcome to the magic world of pokemon. Here you can find all the pokemons you want to adopt.
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
            <p>
              <a class="text-white">Sanji</a>
            </p>
            <p>
              <a class="text-white">Lukee</a>
            </p>
            <p>
              <a class="text-white">Fabulous</a>
            </p>
            <p>
              <a class="text-white">Expert developer</a>
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
            <p><i class="fas fa-home mr-3"></i>Saint Pierre, Moka, Mauritius</p>
            <p><i class="fas fa-envelope mr-3"></i> slj@gmail.com</p>
            <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Follow us</h6>

            <!-- Facebook -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #3b5998"
               href="#!"
               role="button"
               ><i class="fab fa-facebook-f"></i
              ></a>

            <!-- Twitter -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #55acee"
               href="#!"
               role="button"
               ><i class="fab fa-twitter"></i
              ></a>

            <!-- Google -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #dd4b39"
               href="#!"
               role="button"
               ><i class="fab fa-google"></i
              ></a>

            <!-- Instagram -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #ac2bac"
               href="#!"
               role="button"
               ><i class="fab fa-instagram"></i
              ></a>

            <!-- Linkedin -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #0082ca"
               href="#!"
               role="button"
               ><i class="fab fa-linkedin-in"></i
              ></a>
            <!-- Github -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #333333"
               href="#!"
               role="button"
               ><i class="fab fa-github"></i
              ></a>
          </div>
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div
         class="text-center p-3"
         style="background-color: rgba(0, 0, 0, 0.2)"
         >
      © 2024 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/"
         >Magicmon.com</a
        >
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

<!-- End of .container -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "Screenshot_8-3-2024_1253_logotip.online.jpeg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Animal", new_animal_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Animals", my_animals_animals_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Bookings", my_bookings_bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "Screenshot_7-3-2024_11652_www.bing.com.jpeg", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>